lib/sky_web/router.ex
defmodule SkyWeb.Router do
  use SkyWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Sky.Plugs.CurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SkyWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/help", HelpController, :index
    resources "/posts", PostController
    resources "/commodities", CommodityController
    # 注册
    get "/signup", UserController, :new, as: :signup
    post "/signup", UserController, :create, as: :signup
    # 登录
    get "/signin", SessionController, :new, as: :signin
    post "/signin", SessionController, :create, as: :signin
    # 退出
    get "/signout", SessionController, :delete, as: :signout
    # 个人主页
    get "/:mobile", UserController, :show
    # resources "/users", UserController, only: [:index, :edit, :update, :delete]
    resources "/setting", SettingController, only: [:update, :show], singleton: true do
      get("/account", SettingController, :account, as: :account)
      get("/password", SettingController, :password, as: :password)
      get("/profile", SettingController, :profile, as: :profile)
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", SkyWeb do
  #   pipe_through :api
  # end
end

lib/sky_web/controllers/setting_controller.ex
defmodule SkyWeb.SettingController do
  use SkyWeb, :controller
  alias Sky.Accounts

  plug :put_layout, "user.html"
  plug Sky.Plugs.RequireUser # when action in [:index, :show]
  # @intercepted_action ~w(show account password profile)a

  # def action(conn, _) do
  #   if Enum.member?(@intercepted_action, action_name(conn)) do
  #     changeset = Accounts.change_user(current_user(conn))
  #     render(conn, action_name(conn), changeset: changeset)
  #   else
  #     apply(__MODULE__, action_name(conn), [conn, conn.params])
  #   end
  # end

  def profile(conn, _) do
    changeset = Accounts.change_user(current_user(conn))
    render(conn, "profile.html", changeset: changeset)
  end

  def account(conn, _) do
    changeset = Accounts.change_user(current_user(conn))
    render(conn, "account.html", changeset: changeset)
  end

  def password(conn, _) do
    changeset = Accounts.change_user(current_user(conn))
    render(conn, "password.html", changeset: changeset)
  end

  def update(conn, %{"user" => params}) do
    case params["type"] do
      "profile" -> update_profile(conn, params)
      "account" -> update_account(conn, params)
      "password" -> update_password(conn, params)
    end
  end

  # %{"user" => params} = %{"_csrf_token" => "PS4JUC8bFjJbGR89fiptYy1zO0BWJgAAGez5XLQWniPK+hB6l6L41A==", "_method" => "put", "_utf8" => "✓", "id" => "5", "user" => %{"address" => "\b金牛区金府路889号中加水岸9幢2903", "age" => "21", "city" => "成都市", "mobile" => "15881178970", "name" => "六月", "province" => "四川省", "sex" => "男"}
  def update_profile(conn, params) do
    case Accounts.update_user(current_user(conn), params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "Profile updated successfully.")
        |> render(:profile, changeset: Accounts.change_user(user))
        # |> redirect(to: setting_profile_path(conn, :profile))
      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:danger, gettext("Profile updated failed"))
        |> render(:profile, changeset: changeset)
    end
  end

  def update_account(conn, params) do
    case Accounts.update_user_account(current_user(conn), params) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "帐号更新成功")
        # |> render(:account, changeset: Accounts.change_user(user))
        |> redirect(to: setting_account_path(conn, :account))
      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:danger, gettext("帐号更新失败"))
        |> render(:account, changeset: changeset)
    end
  end

  def update_password(conn, params) do
    case Accounts.update_user_password(current_user(conn), params) do
      {:ok, _} ->
        conn
        |> configure_session(drop: true)
        |> put_flash(:info, "密码更新成功")
        |> redirect(to: setting_profile_path(conn, :profile))
      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:danger, "新密码无效")
        |> render(:password, changeset: changeset)
      {:error, reason} ->
        # changeset = Accounts.user_update_password_changeset()
        conn
        |> put_flash(:danger, reason)
        |> redirect(to: setting_password_path(conn, :password))
    end
  end
end

lib/sky_web/views/setting_view.ex
defmodule SkyWeb.SettingView do
  use SkyWeb, :view
end

lib/sky_web/templates/setting/account.html.eex
<h2>更新帐号</h2>
<%= form_for @changeset, setting_path(@conn, :update), [multipart: true], fn f -> %>
  <%= hidden_input f, :type, value: "account" %>
  <div class="form-group">
    <%= label f, :mobile, class: "control-label" %>
    <%= text_input f, :mobile, class: "form-control", readonly: true %>
  </div>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>
  <div class="form-group">
    <%= file_input f, :avatar, class: "form-control" %>
    <%= error_tag f, :avatar %>
  </div>

  <div class="form-group">
    <%= submit "更新", class: "btn btn-primary form-control" %>
  </div>
<% end %>

lib/sky_web/templates/setting/password.html.eex
<h2>更新密码</h2>
<%= form_for @changeset, setting_path(@conn, :update), fn f -> %>
  <%= hidden_input f, :type, value: "password" %>
  <div class="form-group">
    <%= label f, :current_password, class: "control-label" %>
    <%= password_input f, :current_password, class: "form-control", required: true %>
    <%= error_tag f, :current_password %>
  </div>

  <div class="form-group">
    <%= label f, :password, gettext("New Password") %>
    <%= password_input f, :password, class: "form-control", required: true %>
    <%= error_tag f, :password %>
  </div>

  <div class="form-group">
    <%= label f, :password_confirmation, gettext("Confirmation Password") %>
    <%= password_input f, :password_confirmation, class: "form-control", required: true %>
    <%= error_tag f, :password_confirmation %>
  </div>

  <div class="form-group">
    <%= submit "更新", class: "btn btn-primary form-control" %>
  </div>
<% end %>

lib/sky_web/templates/setting/profile.html.eex
<h2>更新个人资料</h2>
<%= form_for @changeset, setting_path(@conn, :update), fn f -> %>
  <%= hidden_input f, :type, value: "profile" %>
  <div class="form-group">
    <%= label f, :mobile, class: "control-label" %>
    <%= text_input f, :mobile, class: "form-control", readonly: true %>
  </div>

  <div class="form-group">
    <%= label f, :age, class: "control-label" %>
    <%= text_input f, :age, class: "form-control" %>
    <%= error_tag f, :age %>
  </div>

  <div class="form-group">
    <%= label f, :sex, class: "control-label" %>
    <%= text_input f, :sex, class: "form-control" %>
    <%= error_tag f, :sex %>
  </div>

  <div class="form-group">
    <%= label f, :province, class: "control-label" %>
    <%= text_input f, :province, class: "form-control" %>
    <%= error_tag f, :province %>
  </div>

  <div class="form-group">
    <%= label f, :city, class: "control-label" %>
    <%= text_input f, :city, class: "form-control" %>
    <%= error_tag f, :city %>
  </div>

  <div class="form-group">
    <%= label f, :address, class: "control-label" %>
    <%= text_input f, :address, class: "form-control" %>
    <%= error_tag f, :address %>
  </div>

  <div class="form-group">
    <%= submit "更新", class: "btn btn-primary form-control" %>
  </div>
<% end %>