lib/sky_web/router.ex
defmodule SkyWeb.Router do
  use SkyWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Sky.Plugs.CurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SkyWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/help", HelpController, :index
    resources "/posts", PostController
    resources "/commodities", CommodityController
    # 注册
    get "/signup", UserController, :new, as: :signup
    post "/signup", UserController, :create, as: :signup
    # 登录
    get "/signin", SessionController, :new, as: :signin
    post "/signin", SessionController, :create, as: :signin
    # 退出
    get "/signout", SessionController, :delete, as: :signout
    # 个人主页
    get "/:mobile", UserController, :show
    # resources "/users", UserController, only: [:index, :edit, :update, :delete]
    resources "/setting", SettingController, only: [:update, :show], singleton: true do
      get("/account", SettingController, :account, as: :account)
      get("/password", SettingController, :password, as: :password)
      get("/profile", SettingController, :profile, as: :profile)
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", SkyWeb do
  #   pipe_through :api
  # end
end

lib/sky/accounts/user.ex
defmodule Sky.Accounts.User do
  use Ecto.Schema
  use Arc.Ecto.Schema
  import Ecto.Changeset
  import Comeonin.Bcrypt

  alias Sky.Accounts.User
  # alias Sky.{
  #   Tags.Tag
  # }


  # 数据结构
  schema "users" do
    field :mobile, :string
    field :name, :string
    field :avatar, Sky.Avatar.Type
    field :password, :string, virtual: true
    field :password_digest, :string
    field :age, :integer
    field :sex, :string
    field :province, :string
    field :city, :string
    field :address, :string
    timestamps()

    has_many :commodities, Sky.Shop.Commodity
    # has_many :topics, Topic, on_delete: :delete_all
  end

  def changeset(user, attrs) do
    permitted = [
      :mobile,
      :name,
      :avatar,
      :age,
      :sex,
      :province,
      :city,
      :address
    ]
    user
    |> cast(attrs, permitted)
    |> validate_required([:mobile])
  end

  @doc """
  用户登录 changeset
  iex(12)> User.login_changeset(user, %{mobile: "Asf", password: "asfasdfasf"})
  #Ecto.Changeset<
    action: nil,
    changes: %{mobile: "Asf", password: "asfasdfasf"},
    errors: [],
    data: #Sky.Accounts.User<>,
    valid?: true
  >
  """
  def login_changeset(user, attrs) do
    user
    |> cast(attrs, [:mobile, :password])
    |> validate_required([:mobile, :password])
    # |> validate_length(:mobile, is: 11)
    # |> validate_format(:mobile, ~r/\d{11}/, message: "手机号码输入错误")
    # |> validate_length(:password, min: 6, max: 15)
  end

  @doc """
  用户注册 changeset
  """
  def register_changeset(%User{} = user, attrs) do
    user
    |> cast(attrs, [:mobile, :password])
    |> validate_required([:mobile, :password])
    |> unique_constraint(:mobile)
    |> validate_format(:mobile, ~r/\d{11}/)
    |> validate_length(:password, min: 6, max: 15)
    |> validate_confirmation(:password, message: "密码两次输入不一至")
    |> hash_password
  end

  @doc """
  修改用户资料 changeset
  """
  def profile_changeset(%User{} = user, attrs) do
    user
    |> cast(attrs, [:age, :sex, :province, :city, :address])
    |> validate_required([:age, :sex, :province, :city, :address])
    |> validate_inclusion(:age, 18..70)
    |> validate_inclusion(:sex, ["男","女"])
    |> validate_length(:province, min: 3, max: 15)
    |> validate_length(:city, min: 2, max: 15)
    |> validate_length(:address, min: 5, max: 30)
  end

  @doc """
  修改帐号 changeset
  """
  def account_changeset(%User{} = user, attrs) do
    user
    |> cast(attrs, [:name])
    |> cast_attachments(attrs, [:avatar])
    |> validate_required([:name, :avatar])
    |> validate_exclusion(:name, ~w(admin superadmin 你大爷))
    |> validate_length(:name, min: 2, max: 10)
  end
  
  @doc """
  修改密码 changeset
  """
  def password_changeset(user, attrs) do
    user
    |> cast(attrs, [:password])
    |> validate_required([:password])
    |> validate_length(:password, min: 6, max: 15)
    |> validate_confirmation(:password, message: "密码两次输入不一至")
    |> hash_password
  end

  @doc """
  用户注册时密码加密
  iex(12)> User.login_changeset(user, %{mobile: "Asf", password: "asfasdfasf"})
  #Ecto.Changeset<
    action: nil,
    changes: %{mobile: "Asf", password: "asfasdfasf"},
    errors: [],
    data: #Sky.Accounts.User<>,
    valid?: true
  >
  """
  defp hash_password(changeset) do
    case changeset do
      %Ecto.Changeset{valid?: true, changes: %{password: password}} -> 
        put_change(changeset, :password_digest, hashpwsalt(password))
      _ ->
        changeset
    end
  end

  # def validate_user(%{valid?: false} = changeset) do
  #   {:error, changeset}
  # end
  
  # def validate_user(changeset) do
  #   with mobile   <- get_field(changeset, :mobile),
  #     password    <- get_field(changeset, :password),
  #     {:ok, user} <- Sky.Accounts.get_by_mobile(mobile),
  #     {:ok, user} <- valid_password(user, password)
  #   do
  #     {:ok, user}
  #   else
  #     {:error, message} -> {:error, add_error(changeset, :mobile, message)}
  #   end
  # end
end

lib/sky_web/controllers/user_controller.ex
defmodule SkyWeb.UserController do
  use SkyWeb, :controller
  alias Sky.Accounts
  plug :put_layout, "user.html"
  plug Sky.Plugs.RequireUser when action in [:index, :show]

  def index(conn, _params) do
    users = Accounts.list_users()
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    changeset = Accounts.change_signup
    render(conn, :new, changeset: changeset)
  end

  def create(conn, %{"user" => params}) do
    case Accounts.create_user(params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User created successfully.")
        |> redirect(to: user_path(conn, :show, user))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  @spec show(Plug.Conn.t(), map()) :: Plug.Conn.t()
  def show(conn, _params) do
    user = current_user(conn) #Accounts.find_user_by_mobile(id)
    render(conn, "show.html", user: user)
    # render(conn, :show,
    #   user: user,
    #   topics: topics,
    #   replies: replies
    # )
  end

  # def edit(conn) do
  #   # user = Accounts.get_user!(id)
  #   changeset = Accounts.change_user(current_user(conn))
  #   render(conn, "edit.html", changeset: changeset)
  #   # render(conn, "edit.html", user: user, changeset: changeset)
  # end

  # %{"user" => params} = %{"_csrf_token" => "PS4JUC8bFjJbGR89fiptYy1zO0BWJgAAGez5XLQWniPK+hB6l6L41A==", "_method" => "put", "_utf8" => "✓", "id" => "5", "user" => %{"address" => "\b金牛区金府路889号中加水岸9幢2903", "age" => "21", "city" => "成都市", "mobile" => "15881178970", "name" => "六月", "province" => "四川省", "sex" => "男"}
  # @spec update(Plug.Conn.t(), map()) :: Plug.Conn.t()
  # def update(conn, %{"user" => params}) do
  #   # user = Accounts.get_user!(id)

  #   case Accounts.update_user(current_user(conn), params) do
  #     {:ok, user} ->
  #       conn
  #       |> put_flash(:info, "User updated successfully.")
  #       # |> redirect(to: user_path(conn, :show, user))
  #       |> render(:show, changeset: Accounts.change_user(user))
  #     {:error, %Ecto.Changeset{} = changeset} ->
  #       # render(conn, "edit.html", user: current_user(conn), changeset: changeset)
  #       conn
  #       |> put_flash(:danger, gettext("Profile updated failed"))
  #       |> render(:show, changeset: changeset)
  #   end
  # end

  # @spec delete(any(), any()) :: none()
  # def delete(conn, _) do
  #   user = current_user(conn)
  #   # Accounts.get_user!(id)
  #   {:ok, _user} = Accounts.delete_user(user)

  #   conn
  #   |> put_flash(:info, "User deleted successfully.")
  #   |> redirect(to: signin_path(conn, :index))
  # end
end

lib/sky_web/views/user_view.ex
defmodule SkyWeb.UserView do
  use SkyWeb, :view
end

lib/sky_web/templates/user/edit.html.eex
<h2>更新个人资料</h2>
<%= form_for @changeset, user_path(@conn, :update, current_user(@conn)), fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>哎呀！出事了！ 请检查以下错误。</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :mobile, class: "control-label" %>
    <%= text_input f, :mobile, class: "form-control", readonly: true %>
    <%= error_tag f, :mobile %>
  </div>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :age, class: "control-label" %>
    <%= text_input f, :age, class: "form-control" %>
    <%= error_tag f, :age %>
  </div>

  <div class="form-group">
    <%= label f, :sex, class: "control-label" %>
    <%= text_input f, :sex, class: "form-control" %>
    <%= error_tag f, :sex %>
  </div>

  <div class="form-group">
    <%= label f, :province, class: "control-label" %>
    <%= text_input f, :province, class: "form-control" %>
    <%= error_tag f, :province %>
  </div>

  <div class="form-group">
    <%= label f, :city, class: "control-label" %>
    <%= text_input f, :city, class: "form-control" %>
    <%= error_tag f, :city %>
  </div>

  <div class="form-group">
    <%= label f, :address, class: "control-label" %>
    <%= text_input f, :address, class: "form-control" %>
    <%= error_tag f, :address %>
  </div>

  <div class="form-group">
    <%= submit "更新", class: "btn btn-primary", style: "width:100%;" %>
  </div>
<% end %>

lib/sky_web/templates/user/index.html.eex
<h2>用户管理</h2>
<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>姓名</th>
      <th>电话</th>
      <th>年龄</th>
      <th>性别</th>
      <th>地址</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.name %></td>
      <td><%= user.mobile %></td>
      <td><%= user.age %></td>
      <td><%= user.sex %></td>
      <td><%= user.address %></td>
      <td class="text-right">
        <span><%= link "查看", to: user_path(@conn, :show, user), class: "btn btn-default btn-xs" %></span>
        <span><%= link "编辑", to: setting_profile_path(@conn, :profile), class: "btn btn-default btn-xs" %></span>
        <span><%= link "删除", to: user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

lib/sky_web/templates/user/new.html.eex
<%= if @changeset.action do %>
  <div class="alert alert-danger">
    <p>哎呀！出事了！ 请检查以下错误。</p>
  </div>
<% end %>
<%= form_for @changeset, signup_path(@conn, :create), fn f -> %>
  <div class="form-group">
    <%= label f, :mobile, class: "control-label" %>
    <%= telephone_input f, :mobile, class: "form-control" %>
    <%= error_tag f, :mobile %>
  </div>

  <div class="form-group">
    <%= label f, :password, class: "control-label" %>
    <%= text_input f, :password, class: "form-control" %>
    <%= error_tag f, :password %>
  </div>

  <div class="form-group">
    <%= label f, :password_confirmation, class: "control-label" %>
    <%= text_input f, :password_confirmation, class: "form-control" %>
    <%= error_tag f, :password_confirmation %>
  </div>

  <div class="form-group">
    <%= submit "注册", class: "btn btn-primary form-control" %>
  </div>
<% end %>

lib/sky_web/templates/user/show.html.eex
<ul>
  <li>
    <img class="thumbnail" src="<%= Sky.Avatar.url({@current_user.avatar, @current_user}, :thumb) %>"/>
  </li>
  <li>
    <strong>姓名:</strong>
    <%= @user.name %>
  </li>

  <li>
    <strong>电话:</strong>
    <%= @user.mobile %>
  </li>

  <li>
    <strong>年龄:</strong>
    <%= @user.age %>
  </li>

  <li>
    <strong>地址:</strong>
    <%= @user.province %><%= @user.city %><%= @user.address %>
  </li>

</ul>

<span><%= link "个人资料", to: setting_profile_path(@conn, :profile) %></span>
<span><%= link "帐号信息", to: setting_account_path(@conn, :account) %></span>
<span><%= link "登录密码", to: setting_password_path(@conn, :password) %></span>