lib/sky_web/router.ex
defmodule SkyWeb.Router do
  use SkyWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Sky.Plugs.CurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SkyWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/help", HelpController, :index
    resources "/posts", PostController
    resources "/commodities", CommodityController
    # 注册
    get "/signup", UserController, :new, as: :signup
    post "/signup", UserController, :create, as: :signup
    # 登录
    get "/signin", SessionController, :new, as: :signin
    post "/signin", SessionController, :create, as: :signin
    # 退出
    get "/signout", SessionController, :delete, as: :signout
    # 个人主页
    get "/:mobile", UserController, :show
    # resources "/users", UserController, only: [:index, :edit, :update, :delete]
    resources "/setting", SettingController, only: [:update, :show], singleton: true do
      get("/account", SettingController, :account, as: :account)
      get("/password", SettingController, :password, as: :password)
      get("/profile", SettingController, :profile, as: :profile)
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", SkyWeb do
  #   pipe_through :api
  # end
end

lib/sky_web/views/layout_view.ex
defmodule SkyWeb.LayoutView do
  use SkyWeb, :view
end

lib/sky_web/templates/layout/_flash.html.eex
<div class="container-full" style="margin-top: 10px;">
  <%= for item <- ~w(danger success warning info)a do %>
    <%= if get_flash(@conn, item) do %>
    <div class="alert alert-<%= item %> text-center alert-dismissible fade show" role="alert">
      <%= get_flash(@conn, item) %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <% end %>
  <% end %>
</div>

lib/sky_web/templates/layout/_footer.html.eex
<footer class="footer fixed-bottom" id="footer">
  <div class="d-flex justify-content-around" style="height:3rem;">
    <div class="p-2">😀<br />大家</div>
    <div class="p-2">记录</div>
    <div class="p-2">我的</div>
  </div>
</footer>

lib/sky_web/templates/layout/_header.html.eex
<header class="user">
  <nav role="navigation">
    <div class="navbar-header float-left" id="navbar-header">
      <a href="/" class="navbar-brand">
        <b>试一把</b></a>
    </div>
    <ul class="nav justify-content-end">
      <%= if current_user(@conn) do %>
        <%= render "_navigation_item.html", conn: @conn, text: current_user(@conn).mobile, url: user_path(@conn, :show, current_user(@conn).mobile) %>
        <%= render "_navigation_item.html", conn: @conn, text: "退出", url: signout_path(@conn, :delete) %>
      <% else %>
        <%= render "_navigation_item.html", conn: @conn, text: "注册", url: signup_path(@conn, :new) %>
        <%= render "_navigation_item.html", conn: @conn, text: "登录", url: signin_path(@conn, :new) %>
      <% end %>
    </ul>
  </nav>
  <span class="logo"></span>
</header>

lib/sky_web/templates/layout/_navigation_item.html.eex
<li class="nav-item"><%= link @text, to: @url, class: 'nav-link' %></li>

lib/sky_web/templates/layout/_user_header.html.eex
<header class="user">
  <%= if current_user(@conn) do %>
  <div class="account">
    <div class="row">
      <div class="col-2 col-sm-2 col-md-2" style="margin:0;padding:0;">
        <div class="avatar"><img class="rounded-circle" src="<%= Sky.Avatar.url({@current_user.avatar, @current_user}, :thumb) %>"/></div>
      </div>
      <div class="col-10 col-sm-10 col-md-10" style="margin:0;padding:0;">
        <div class="profile">
          <div class="info">
            <h1><%= link(current_user(@conn).name, to: user_path(@conn, :show, current_user(@conn).mobile)) %></h1>
            <div class="name">
              子非鱼，安知鱼之乐
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="set">设置</div>
  </div>
  <% end %>
</header>

lib/sky_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="cn">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="没事玩下Elixir">
    <meta name="author" content="笑笑">
    <title>试一把</title>
    <link rel="stylesheet" href=<%= static_path(@conn, "/js/app.css") %> />
    <script src=<%= static_path(@conn, "/js/app.js") %>></script>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "_header.html", assigns %>
      <%= render "_flash.html", assigns %>
      <div class="main">
        <%= render @view_module, @view_template, assigns %>
      </div>
      <%= render "_footer.html", assigns %>
    </div>
  </body>
</html>

lib/sky_web/templates/layout/user.html.eex
<!DOCTYPE html>
<html lang="cn">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="没事玩下Elixir">
    <meta name="author" content="何永">
    <title>试一把</title>
    <link rel="stylesheet" href=<%= static_path(@conn, "/css/user.css") %> />
    <script src=<%= static_path(@conn, "/js/user.js") %>></script>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "_user_header.html", assigns %>
      <div class="main">
        <%= render "_flash.html", assigns %>
        <%= render @view_module, @view_template, assigns %>
      </div>
      <%= render "_footer.html", assigns %>
    </div>
  </body>
</html>